version: '3.3'

volumes:
  postgres_data:
  static_value:

services:
  database:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always

  web:
    image: talpik/yamdb:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - database
    env_file:
      - ./.env
    volumes:
      - ./static_value:/code/static

  nginx:
    image: nginx:latest
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static_value:/code/static/
      - ./nginx/logs:/var/log/nginx
    depends_on:
      - web
    ports:
      - "80:80"
