version: '3.8'

volumes:
  postgres_data:
  static_value:


networks:
  private:
  # This instructions for SSL auto
  # proxy:
    # external: true

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    restart: always
    networks: 
      - private
  web:
    image: talpik/yamdb
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - ./.env
    volumes:
      - ./static_value:/code/static
    networks: 
      - private
  nginx:
    image: nginx:1.19.1
    restart: always
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./static_value:/code/static/
    depends_on:
      - web
    ports:
      - "80:80"
    networks: 
      - private

    # This instructions for SSL auto
    # environment:
      # VIRTUAL_HOST: web.talpa.ru
      # LETSENCRIPT_HOST: web.talpa.ru
      # LETSENCRIPT_EMAIL: talpa1989@gmail.com
    # networks:
      # - proxy
    # expose:
      # - 80
